"""
report_generator_node.py — Nodo 6 del Meeting Intelligence Agent

Responsabilidad: generar el informe final en dos formatos:
- markdown: para que el usuario lo lea y descargue
- json: para que el frontend lo renderice en cards estructuradas

El JSON no es para RAG (el RAG ya está en el indexer con pgvector).
El JSON es para que el frontend pueda renderizar cada categoría
por separado sin tener que parsear el markdown.
"""

from __future__ import annotations

from datetime import datetime

from ..state import MeetingState


def report_generator_node(state: MeetingState) -> dict:
    """
    Nodo 6: genera el informe final en markdown y JSON.

    Returns:
        dict con:
        - report_markdown: informe completo en markdown
        - report_json: informe estructurado para el frontend
    """
    print("[ReportGeneratorNode] Generando informe final...")

    if state.get("error"):
        return {}

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    title = state.get("meeting_title", "Untitled Meeting")
    duration = state.get("audio_duration_seconds")
    language = state.get("transcription_language", "es")

    decisions = state.get("decisions", [])
    action_items = state.get("action_items", [])
    open_questions = state.get("open_questions", [])
    pending_topics = state.get("pending_topics", [])
    executive_summary = state.get("executive_summary", "")
    key_topics = state.get("key_topics", [])
    meeting_id = state.get("meeting_id", "")
    chunks_indexed = state.get("chunks_indexed", 0)

    # Formateamos la duración para el informe
    duration_str = _format_duration(duration) if duration else "N/A"

    markdown = _build_markdown(
        title=title,
        timestamp=timestamp,
        duration_str=duration_str,
        language=language,
        executive_summary=executive_summary,
        key_topics=key_topics,
        decisions=decisions,
        action_items=action_items,
        open_questions=open_questions,
        pending_topics=pending_topics,
        meeting_id=meeting_id,
        chunks_indexed=chunks_indexed,
    )

    report_json = {
        "meeting_id": meeting_id,
        "title": title,
        "timestamp": timestamp,
        "duration": duration_str,
        "language": language,
        "executive_summary": executive_summary,
        "key_topics": key_topics,
        "decisions": decisions,
        "action_items": action_items,
        "open_questions": open_questions,
        "pending_topics": pending_topics,
        "stats": {
            "chunks_indexed": chunks_indexed,
            "total_decisions": len(decisions),
            "total_action_items": len(action_items),
            "total_open_questions": len(open_questions),
            "total_pending_topics": len(pending_topics),
        },
    }

    print(
        f"[ReportGeneratorNode] Informe generado. "
        f"Decisiones: {len(decisions)}, "
        f"Action items: {len(action_items)}, "
        f"Preguntas: {len(open_questions)}"
    )

    return {
        "report_markdown": markdown,
        "report_json": report_json,
    }


def _build_markdown(
    title: str,
    timestamp: str,
    duration_str: str,
    language: str,
    executive_summary: str,
    key_topics: list[str],
    decisions: list[dict],
    action_items: list[dict],
    open_questions: list[dict],
    pending_topics: list[dict],
    meeting_id: str,
    chunks_indexed: int,
) -> str:
    """Construye el informe completo en markdown."""

    # Sección de decisions
    decisions_text = (
        "\n".join([f"- **{d.get('text', '')}**\n  > {d.get('context', '')}" for d in decisions])
        or "_No decisions recorded._"
    )

    # Sección de action items con prioridad
    def priority_emoji(p: str) -> str:
        return {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(p.lower(), "⚪")

    action_items_text = (
        "\n".join(
            [
                f"- {priority_emoji(a.get('priority', 'medium'))} **{a.get('task', '')}**\n"
                f"  Owner: `{a.get('owner', 'unassigned')}` · Deadline: `{a.get('deadline', 'not specified')}`"
                for a in action_items
            ]
        )
        or "_No action items recorded._"
    )

    # Sección de preguntas abiertas
    questions_text = (
        "\n".join(
            [f"- ❓ {q.get('question', '')}\n  > {q.get('context', '')}" for q in open_questions]
        )
        or "_No open questions._"
    )

    # Sección de temas pendientes
    pending_text = (
        "\n".join(
            [f"- 📌 **{p.get('topic', '')}** — {p.get('reason', '')}" for p in pending_topics]
        )
        or "_No pending topics._"
    )

    # Temas clave
    topics_text = ", ".join(key_topics) if key_topics else "N/A"

    return f"""# Meeting Intelligence Report — {title}

> Generated by Meeting Intelligence Agent | {timestamp}
> Duration: {duration_str} · Language: {language.upper()} · ID: `{meeting_id}`

---

## 📋 Executive Summary

{executive_summary or "_No summary available._"}

**Key Topics:** {topics_text}

---

## ✅ Decisions Made ({len(decisions)})

{decisions_text}

---

## 📌 Action Items ({len(action_items)})

{action_items_text}

---

## ❓ Open Questions ({len(open_questions)})

{questions_text}

---

## 🔄 Pending Topics ({len(pending_topics)})

{pending_text}

---

## 📊 Stats

| Metric | Value |
|---|---|
| Decisions | {len(decisions)} |
| Action Items | {len(action_items)} |
| Open Questions | {len(open_questions)} |
| Pending Topics | {len(pending_topics)} |
| Chunks Indexed | {chunks_indexed} |

---

*Report generated by Meeting Intelligence Agent — github.com/LanderIglesias/LanderWorks-Agents*
"""


def _format_duration(seconds: float) -> str:
    """Convierte segundos en formato legible: 1h 23m 45s."""
    seconds = int(seconds)
    hours = seconds // 3600
    minutes = (seconds % 3600) // 60
    secs = seconds % 60

    if hours > 0:
        return f"{hours}h {minutes}m {secs}s"
    elif minutes > 0:
        return f"{minutes}m {secs}s"
    else:
        return f"{secs}s"
